/**
 * 편집기(Monaco) 테마 — 앱(XGEN)과 같은 색. VS Code 의 vs·vs-dark 를 바탕으로 문법 색은 물려받고
 * 판·줄 번호·현재 줄·선택·커서·떠 있는 창(제안·설명)·비교 색만 앱 팔레트로 바꾼다.
 */
import type { MonacoApi } from './types';

const LIGHT: Record<string, string> = {
  'editor.background': '#ffffff',
  'editor.foreground': '#1d1f23',
  'editorGutter.background': '#ffffff',
  'editorLineNumber.foreground': '#abb1ba',
  'editorLineNumber.activeForeground': '#40444d',
  'editor.lineHighlightBackground': '#f8f9fa',
  'editor.lineHighlightBorder': '#00000000',
  'editor.selectionBackground': '#305eeb33',
  'editor.inactiveSelectionBackground': '#305eeb1f',
  'editor.selectionHighlightBackground': '#305eeb1a',
  'editor.wordHighlightBackground': '#305eeb14',
  'editor.wordHighlightStrongBackground': '#305eeb1f',
  'editor.findMatchBackground': '#f59f0059',
  'editor.findMatchHighlightBackground': '#f59f0033',
  'editorCursor.foreground': '#305eeb',
  'editorIndentGuide.background1': '#eef0f3',
  'editorIndentGuide.activeBackground1': '#d0d5dd',
  'editorWhitespace.foreground': '#d0d5dd',
  'editorBracketMatch.background': '#305eeb14',
  'editorBracketMatch.border': '#305eeb55',
  'editorWidget.background': '#ffffff',
  'editorWidget.border': '#e4e7ec',
  'editorSuggestWidget.background': '#ffffff',
  'editorSuggestWidget.border': '#e4e7ec',
  'editorSuggestWidget.selectedBackground': '#305eeb1a',
  'editorSuggestWidget.highlightForeground': '#305eeb',
  'editorHoverWidget.background': '#ffffff',
  'editorHoverWidget.border': '#e4e7ec',
  'editorStickyScroll.background': '#ffffff',
  'editorStickyScrollHover.background': '#f8f9fa',
  'minimap.background': '#ffffff',
  'editorOverviewRuler.border': '#00000000',
  'scrollbar.shadow': '#00000000',
  'scrollbarSlider.background': '#1d1f2314',
  'scrollbarSlider.hoverBackground': '#1d1f2326',
  'scrollbarSlider.activeBackground': '#1d1f2333',
  focusBorder: '#305eeb66',
  'input.background': '#f8f9fa',
  'input.border': '#e4e7ec',
  'inputOption.activeBackground': '#305eeb1a',
  'inputOption.activeBorder': '#305eeb55',
  'list.activeSelectionBackground': '#305eeb1a',
  'list.activeSelectionForeground': '#1d1f23',
  'list.hoverBackground': '#f2f4f7',
  'menu.background': '#ffffff',
  'menu.selectionBackground': '#f2f4f7',
  'menu.selectionForeground': '#1d1f23',
  'diffEditor.insertedTextBackground': '#2eb14629',
  'diffEditor.removedTextBackground': '#e0313124',
  'diffEditor.insertedLineBackground': '#2eb14612',
  'diffEditor.removedLineBackground': '#e0313110',
  'diffEditor.diagonalFill': '#e4e7ec',
};

const DARK: Record<string, string> = {
  'editor.background': '#1d1f23',
  'editor.foreground': '#e7e9ee',
  'editorGutter.background': '#1d1f23',
  'editorLineNumber.foreground': '#5c6370',
  'editorLineNumber.activeForeground': '#b6bcc6',
  'editor.lineHighlightBackground': '#22252b',
  'editor.lineHighlightBorder': '#00000000',
  'editor.selectionBackground': '#5b82ff47',
  'editor.inactiveSelectionBackground': '#5b82ff26',
  'editor.selectionHighlightBackground': '#5b82ff26',
  'editor.wordHighlightBackground': '#5b82ff1f',
  'editor.wordHighlightStrongBackground': '#5b82ff2e',
  'editor.findMatchBackground': '#f59f0066',
  'editor.findMatchHighlightBackground': '#f59f0038',
  'editorCursor.foreground': '#7d9cff',
  'editorIndentGuide.background1': '#2b2f37',
  'editorIndentGuide.activeBackground1': '#3a3f49',
  'editorWhitespace.foreground': '#3a3f49',
  'editorBracketMatch.background': '#5b82ff1f',
  'editorBracketMatch.border': '#7d9cff66',
  'editorWidget.background': '#22252b',
  'editorWidget.border': '#2b2f37',
  'editorSuggestWidget.background': '#22252b',
  'editorSuggestWidget.border': '#2b2f37',
  'editorSuggestWidget.selectedBackground': '#5b82ff2e',
  'editorSuggestWidget.highlightForeground': '#7d9cff',
  'editorHoverWidget.background': '#22252b',
  'editorHoverWidget.border': '#2b2f37',
  'editorStickyScroll.background': '#1d1f23',
  'editorStickyScrollHover.background': '#22252b',
  'minimap.background': '#1d1f23',
  'editorOverviewRuler.border': '#00000000',
  'scrollbar.shadow': '#00000000',
  'scrollbarSlider.background': '#ffffff14',
  'scrollbarSlider.hoverBackground': '#ffffff24',
  'scrollbarSlider.activeBackground': '#ffffff33',
  focusBorder: '#7d9cff66',
  'input.background': '#22252b',
  'input.border': '#2b2f37',
  'inputOption.activeBackground': '#5b82ff2e',
  'inputOption.activeBorder': '#7d9cff66',
  'list.activeSelectionBackground': '#5b82ff2e',
  'list.activeSelectionForeground': '#e7e9ee',
  'list.hoverBackground': '#272a31',
  'menu.background': '#22252b',
  'menu.selectionBackground': '#272a31',
  'menu.selectionForeground': '#e7e9ee',
  'diffEditor.insertedTextBackground': '#3fb95033',
  'diffEditor.removedTextBackground': '#ff6b6b2e',
  'diffEditor.insertedLineBackground': '#3fb95014',
  'diffEditor.removedLineBackground': '#ff6b6b12',
  'diffEditor.diagonalFill': '#2b2f37',
};

let defined = false;

/** 앱 색의 편집기 테마(`xgen-light`·`xgen-dark`)를 한 번 정의한다. */
export function defineXgenThemes(monaco: MonacoApi): void {
  if (defined) return;
  defined = true;
  monaco.editor.defineTheme('xgen-light', { base: 'vs', inherit: true, rules: [], colors: LIGHT });
  monaco.editor.defineTheme('xgen-dark', { base: 'vs-dark', inherit: true, rules: [], colors: DARK });
}
