plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}
group = 'com.plateerlab.xgendex'
version = '0.1.0'
android {
  namespace 'expo.modules.xgennativedevice'
  defaultConfig { versionCode 1; versionName '0.1.0' }
}
dependencies {
  implementation 'com.squareup.okhttp3:okhttp:4.9.2'
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'com.squareup.okhttp3:mockwebserver:4.9.2'
  testImplementation 'com.squareup.okhttp3:okhttp-tls:4.9.2'
}
